/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EndQuiz.java
 *
 * Created on 28-Jan-2011, 18:18:46
 */

package Project;
import java.sql.*;

/**
 *
 * @author kk
 */
public class EndQuiz extends javax.swing.JFrame {

    /** Creates new form EndQuiz */
    public EndQuiz(int pupilPoints2,int quiznum,String pupilnum) {//pass over the the points, quiz number and the pupil number from the the previous form (Question 2) for the pupil who has doen the quiz
        initComponents();
        addScore(pupilPoints2,quiznum,pupilnum);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMessge = new javax.swing.JLabel();
        lblMessage2 = new javax.swing.JLabel();
        btnMain = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "End of Quiz", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        lblMessge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMessge.setText("WELL DONE! You have know completed the quiz.");

        lblMessage2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMessage2.setText("Your score have been added to the Database");

        btnMain.setText("Main Menu");
        btnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/resources/econ_thumbsup[1].gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMessge)
                    .addComponent(lblMessage2))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(btnMain)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage2)
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btnMain)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainActionPerformed
        //this displays the main menu
        this.dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_btnMainActionPerformed
public void addScore(int pupilPoints2,int quiznum,String pupilnum){
    //add the pupils score to the database
   try{
       DatabaseConnect.init();
       Connection conn = DatabaseConnect.getConnection();
       Statement stmt = conn.createStatement();
       stmt.execute("INSERT INTO QUIZ_ATTEMPT (QUIZ_NUMBER,PUPIL_NUMBER,PUPIL_POINTS)VALUES ("+quiznum+",'"+pupilnum+"',"+pupilPoints2+")");//insert the record
       stmt.close();
       conn.close();
   }
   catch(Exception ex){
       System.err.print("SQLException: ");
       System.err.println(ex.getMessage());
   }
}//end method
    /**
    * @param args the command line arguments
    */
    /**
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EndQuiz().setVisible(true);
            }
        });
    }
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMessage2;
    private javax.swing.JLabel lblMessge;
    // End of variables declaration//GEN-END:variables

}
