/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectPupil.java
 *
 * Created on 13-Jan-2011, 17:41:22
 */

package Project;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kk
 */
public class SelectPupil extends javax.swing.JFrame {

    /** Creates new form SelectPupil */
    public SelectPupil() {
        initComponents();
        displayData();//display all pupils
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWel1 = new javax.swing.JLabel();
        lblWel2 = new javax.swing.JLabel();
        lblWel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuiz = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Pupil For Quiz");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Pupil for Quiz", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        lblWel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblWel1.setText("Below is a table that shows every Pupil that has been entered into the database ");

        lblWel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblWel2.setText("the table shows Pupil Number, Pupil Name and their difficulty set by yourself.");

        lblWel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblWel3.setText("Select the Pupil you wish to take part in the quiz:");

        tblQuiz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pupil Number", "First Name", "Last Name", "Skill Level"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblQuiz);
        tblQuiz.getColumnModel().getColumn(0).setResizable(false);
        tblQuiz.getColumnModel().getColumn(1).setResizable(false);
        tblQuiz.getColumnModel().getColumn(2).setResizable(false);
        tblQuiz.getColumnModel().getColumn(3).setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWel1)
                    .addComponent(lblWel3)
                    .addComponent(lblWel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnStart.setText("Start Quiz");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnMenu.setText("Back to Main Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("Tahoma", 0, 12));
        lblMessage.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(lblMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(btnMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStart)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMenu, btnStart});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnMenu)
                    .addComponent(lblMessage))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // get the values from the table to start a new quiz
        getPupil();
    }//GEN-LAST:event_btnStartActionPerformed

    public void displayData(){
        //display all pupils in the database with the skill level that they have been set
        String pupilNum = "";
        String first = "";
        String last = "";
        String skill = "";
        try{
            DatabaseConnect.init();
            Connection conn = DatabaseConnect.getConnection();
            Statement stmt = conn.createStatement();
            String query = "SELECT PUPIL_NUMBER,PUPIL_FIRST_NAME,PUPIL_LAST_NAME,SKILL_LEVEL FROM PUPILS ORDER BY PUPIL_NUMBER";
            ResultSet result = stmt.executeQuery(query);
            DefaultTableModel model = (DefaultTableModel)tblQuiz.getModel();
            while (model.getRowCount()>0)
            {
                model.removeRow(0);
            }
            if (result != null)
            {
                while (result.next())
                {
                pupilNum = result.getString("PUPIL_NUMBER");
                first = result.getString("PUPIL_FIRST_NAME");
                last = result.getString("PUPIL_LAST_NAME");
                skill = result.getString("SKILL_LEVEL");
                model.addRow(new Object[]{pupilNum,first,last,skill});
                }
            }
            else
            {
                while (model.getRowCount()>0)
                {
                    model.removeRow(0);
                }
                lblMessage.setText("There are no Pupils in the database");
            }//END ELSE
            stmt.close();
            conn.close();
            result.close();
        }//end try
        catch(Exception ex){
            System.err.print("SQLException: ");
            System.err.println(ex.getMessage());
        }//END CATCH
    }//END METHOD DISPLAYDATA
    public void getPupil(){
        //get pupil details from the table to start a new quiz
        int row = tblQuiz.getSelectedRow();
        try{
            if (row == -1)
            {
                throw new Exception ("Row not selected");
            }
            else
            {
                String pupilNum = (String)tblQuiz.getValueAt(row, 0);
                String first = (String)tblQuiz.getValueAt(row, 1);
                String last = (String)tblQuiz.getValueAt(row, 2);
                String skill = (String)tblQuiz.getValueAt(row, 3);
                new SelectQuiz(pupilNum,first,last,skill).setVisible(true);//opens a new window to select a quix for the pupil to do
                this.dispose();
            }
        }
        catch(Exception e){
            lblMessage.setText(e.getMessage());
        }
    }//END METHOD
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectPupil().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnStart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblWel1;
    private javax.swing.JLabel lblWel2;
    private javax.swing.JLabel lblWel3;
    private javax.swing.JTable tblQuiz;
    // End of variables declaration//GEN-END:variables

}
